{"trial_id": "19", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "BATCH_SIZE", "default": 16, "conditions": [], "values": [16, 32, 64], "ordered": true}}, {"class_name": "Float", "config": {"name": "l2_reg", "default": 1e-05, "conditions": [], "min_value": 1e-05, "max_value": 0.01, "step": null, "sampling": "log"}}, {"class_name": "Int", "config": {"name": "units", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "l2_reg_2", "default": 1e-05, "conditions": [], "min_value": 1e-05, "max_value": 0.01, "step": null, "sampling": "log"}}, {"class_name": "Float", "config": {"name": "dropout_rate", "default": 0.3, "conditions": [], "min_value": 0.3, "max_value": 0.7, "step": 0.1, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "TRAIN_DROPOUT", "default": 0.2, "conditions": [], "min_value": 0.2, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "TRAIN_LR", "default": 0.0001, "conditions": [], "min_value": 0.0001, "max_value": 0.01, "step": null, "sampling": "log"}}], "values": {"BATCH_SIZE": 32, "l2_reg": 0.0018095447285904397, "units": 96, "l2_reg_2": 2.3205173224929395e-05, "dropout_rate": 0.5, "TRAIN_DROPOUT": 0.4, "TRAIN_LR": 0.0023484415428291594}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/tensorflow/python/eager/execute.py\", line 59, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node adam/truediv_27 defined at (most recent call last):\n  File \"/Users/federicaamato/Desktop/FER_pattlite/patt-lite/hyperparameters_prova.py\", line 174, in <module>\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 320, in fit\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 121, in one_step_on_iterator\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 108, in one_step_on_data\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 73, in train_step\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/optimizers/base_optimizer.py\", line 291, in apply_gradients\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/optimizers/base_optimizer.py\", line 356, in apply\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/optimizers/base_optimizer.py\", line 419, in _backend_apply_gradients\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/optimizer.py\", line 121, in _backend_update_step\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/optimizer.py\", line 135, in _distributed_tf_update_step\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/optimizer.py\", line 132, in apply_grad_to_update_var\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/optimizers/adam.py\", line 147, in update_step\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/ops/numpy.py\", line 5553, in divide\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/sparse.py\", line 780, in sparse_wrapper\n\n  File \"/Users/federicaamato/anaconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/numpy.py\", line 2246, in divide\n\nIncompatible shapes: [0] vs. [96,8]\n\t [[{{node adam/truediv_27}}]] [Op:__inference_one_step_on_iterator_239581]\n"}